export const CONST_APIS = {
  // SERVER_URL: "http://192.168.245.174:8010/api/member",
  SERVER_URL: "https://jscbe.nguyenkimcomputer.vn/api/member",
  DOMAIN: "https://nguyenkimcomputer.vn",
  FEATURES: {
    AUTH: {
      AUTH: "auth",
      LOGIN: "login",
      REGISTER: "register",
      LOGOUT: "logout",
      FORGET_PASSWORD: "forgot-password",
      RESET_PASSWORD: "reset-password",
    },
    MODEL: {
      RECRUITMENT: "recruitment",
      PROMOTION: "promotion",
      QUOTE: "quote",
      SERVICE: "service",
      SUPPORT: "support",
      SLUG: "slug",
      CART: "cart",
      CATEGORY: "category",
      MENU: "menu",
      ADVERTISE: "advertise",
      ADDRESS: "address",
      BUILD_PC: "build-pc",
      PRODUCT: "product",
      NEWS: "news",
      ORDER: "order",
      FAVORITES: "favorites",
      FOOTER: "footer",
      ABOUT: "about",
      POLICY: "policy",
      ADVISE: "advise",
      FAQS: "faqs",
      CONTACT: "contact",
      EVENT_CHECKIN: "participants",
    },
  },
};

export const CONST_APIS_COMMON = {
  ME: "me",
  META: "meta",
  PRODUCT_HOT: "product-hot",
  PRODUCT_BY_CATEGORY: "product-by-category",
  PRODUCT_RECOMMEND: "get-product-recommend",
  PRODUCT_NOTIFY_REGISTER: "notify-register",
  ADD: "add",
  UPDATE: "update",
  DELETE: "delete",
  TOGGLE: "toggle",
  GET_ALL: "get-all",
  FILTER: "filter",
  QUOTE: "quote",
  SEARCH: "search",
  GET_PARENT: "get-parent",
  CHECKOUT: "checkout",
  EXPORT: "export",
  TAKE_FIVE_NEWS: "take-5-news",
  CHECK_SLUGS: "check-slugs",
  GET_PROPERTIES_PRODUCT: "get-properties-product",
  GET_DESCRIPTION: "get-description",
  GET_RELATED_PRODUCT: "get-related-product",
  CATEGORY: "category",
  TAKE_5_PROMOTION: "take-5",
  NEW: "new",
  PROMOTION: "promotion",
  TOP_VIEW: "top-view",
  PRODUCTS_VIEWED: "products-viewed",
  CHECK_META: "check-meta",
  SCHEMA: "schema",
  GET_LIST: "get-list",
  GET_CATEGORY: "get-category",
  RELATED: "related",
  COMPARE: "compare",
  DOWNLOAD: "download",
  BEST_SELLERS: "best-sellers",
  CHECK_TOKEN: "check-token",
  GOOGLE: "google",
  GOOGLE_REDIRECT: "auth/google",
  CALLBACK: "callback",
  BULK_DELETE: "bulk-delete",
  PARTICIPANTS_DELETE: "participants-delete",
  IMPORT: "import",
  GET_INFORMATION: "get-information",
  FLASH_SALE: "flash-sale",
};
