import type { ThemeConfig } from "@/theme/types";

export const christmasTheme: ThemeConfig = {
  key: "christmas",
  name: "Theme Noel",
  status: "published",
  fallbackTheme: "default",
  previewMode: true,
  colors: {
    pageBg: "#FFF8F0",
    pageBgRgb: "255, 248, 240",
    sectionBg: "#FFFFFF",
    sectionSoft: "#FFF1E8",
    surface: "#FFFFFF",
    primary: "#B71C1C",
    primaryHover: "#8F1117",
    primarySoft: "#FFF1E8",
    primaryStrong: "#185E20",
    primaryDeep: "#0F3F1A",
    primaryGlow: "#D4AF37",
    primaryHsl: "0 73% 41%",
    primaryForegroundHsl: "0 0% 100%",
    secondaryHsl: "32 100% 97%",
    secondaryForegroundHsl: "132 58% 23%",
    cardHsl: "0 0% 100%",
    cardForegroundHsl: "343 17% 15%",
    foregroundHsl: "343 17% 15%",
    mutedHsl: "28 69% 96%",
    mutedForegroundHsl: "0 6% 40%",
    borderHsl: "33 43% 85%",
    inputHsl: "33 43% 85%",
    ringHsl: "45 64% 52%",
    accentHsl: "45 64% 52%",
    accentForegroundHsl: "343 17% 15%",
    text: "#2D202D",
    mutedText: "#6B6161",
    border: "#F2E6D6",
    price: "#C1121F",
    cta: "#B71C1C",
    ctaHover: "#8F1117",
    ctaForeground: "#FFFFFF",
    badgeBg: "#C1121F",
    badgeText: "#FFFFFF",
    badgeBorder: "#E8B9B9",
    navBg: "#FFFFFF",
    navText: "#2D202D",
    footerBg: "#FFF8F0",
    footerText: "#2D202D",
  },
  assets: {},
  effects: {
    snow: { enabled: true, intensity: "low", disableMobile: true },
    lights: { enabled: true, intensity: "low" },
    glow: { enabled: true },
    reducedMotionSafe: true,
  },
  pages: {
    home: {
      enabled: true,
      decorationLevel: "high",
      sectionOrder: [
        "topCampaign",
        "hero",
        "quickCategories",
        "benefits",
        "topSelling",
        "flashSale",
        "categoriesProducts",
        "middleCampaign",
        "featuredCategories",
        "promotions",
      ],
      hiddenSections: [],
    },
    category: {
      enabled: true,
      decorationLevel: "medium",
      insertCampaignBanner: true,
    },
    product: {
      enabled: true,
      decorationLevel: "medium",
      showGiftBlock: true,
    },
    cart: {
      enabled: true,
      decorationLevel: "low",
    },
    checkout: {
      enabled: true,
      decorationLevel: "minimal",
    },
  },
};
