import type { ThemeConfig } from "@/theme/types";

export const defaultTheme: ThemeConfig = {
  key: "default",
  name: "Theme mac dinh",
  status: "published",
  fallbackTheme: "default",
  previewMode: false,
  colors: {
    pageBg: "#F1F8FE",
    pageBgRgb: "241, 248, 254",
    sectionBg: "#FFFFFF",
    sectionSoft: "#FFF9DD",
    surface: "#FFFFFF",
    primary: "#FED41B",
    primaryHover: "#E2B90A",
    primarySoft: "#FFF9DD",
    primaryStrong: "#7A6300",
    primaryDeep: "#493B00",
    primaryGlow: "#FDE68A",
    primaryHsl: "47 99% 55%",
    primaryForegroundHsl: "221 39% 11%",
    secondaryHsl: "205 75% 97%",
    secondaryForegroundHsl: "222 24% 16%",
    cardHsl: "0 0% 100%",
    cardForegroundHsl: "222 24% 16%",
    foregroundHsl: "222 24% 16%",
    mutedHsl: "220 20% 96%",
    mutedForegroundHsl: "220 10% 42%",
    borderHsl: "220 14% 87%",
    inputHsl: "220 14% 87%",
    ringHsl: "47 99% 55%",
    accentHsl: "47 99% 55%",
    accentForegroundHsl: "222 24% 16%",
    text: "#1E293B",
    mutedText: "#64748B",
    border: "#E2E8F0",
    price: "#DC2626",
    cta: "#FED41B",
    ctaHover: "#E2B90A",
    ctaForeground: "#0F172A",
    badgeBg: "#FFF9DD",
    badgeText: "#7A6300",
    badgeBorder: "#FED41B",
    navBg: "#FFFFFF",
    navText: "#0F172A",
    footerBg: "#FFFFFF",
    footerText: "#0F172A",
  },
  assets: {},
  effects: {
    snow: { enabled: false, intensity: "low", disableMobile: true },
    lights: { enabled: false, intensity: "low" },
    glow: { enabled: false },
    reducedMotionSafe: true,
  },
  pages: {
    home: {
      enabled: true,
      decorationLevel: "none",
      sectionOrder: [
        "hero",
        "groupBanner",
        "topSelling",
        "flashSale",
        "categoriesProducts",
        "middleBanner",
        "featuredCategories",
        "sideBanners",
        "promotions",
      ],
      hiddenSections: [],
    },
    category: {
      enabled: true,
      decorationLevel: "none",
      insertCampaignBanner: false,
    },
    product: {
      enabled: true,
      decorationLevel: "none",
      showGiftBlock: true,
    },
    cart: {
      enabled: true,
      decorationLevel: "none",
    },
    checkout: {
      enabled: true,
      decorationLevel: "none",
    },
  },
};
